# Generated by Django 4.2.1 on 2023-05-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("spine", models.IntegerField(primary_key=True, serialize=False)),
                ("movie", models.CharField(max_length=200)),
                ("director", models.CharField(max_length=200)),
                ("media_type", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("runtime", models.IntegerField()),
                ("isColor", models.CharField(max_length=50)),
                ("aspect_ratio", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("isBluRay_available", models.BooleanField()),
                ("isDVD_available", models.BooleanField()),
                (
                    "BluRay_price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "DVD_price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("poster_url", models.URLField()),
                ("page_url", models.URLField()),
                ("thumb_url", models.URLField()),
            ],
        ),
    ]
