# Generated by Django 4.2.1 on 2023-05-07 17:50

from django.db import migrations
from movie.models import Movie
import csv

def populate_movie_table(apps, schema_editor):
    # add code to populate movie table from criterion_clean.csv file
    with open('criterion_cleaned.csv', newline='', encoding="utf-8") as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='"')
        next(reader) # skip header row
        for row in reader:
            movie = Movie(
                spine=row[0],
                movie=row[1],
                director=row[2],
                media_type=row[3],
                country=row[4],
                year=row[5],
                runtime=row[6],
                isColor=row[7],
                aspect_ratio=row[8],
                language=row[9],
                isBluRay_available=row[10],
                isDVD_available=row[11],
                BluRay_price=row[12],
                DVD_price=row[13],
                poster_url=row[14],
                page_url=row[15],
                thumb_url=row[16]
            )
            movie.save()

class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_movie_table),
    ]
