# Generated by Django 4.2.1 on 2023-05-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_auto_20230507_2350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
